# Generated by Django 4.2.4 on 2023-08-07 15:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0002_alter_post_desc_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
